// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdjustVolume(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AdjustVolume'](arg1, arg2, arg3, arg4);
}

export function CheckFFmpeg() {
  return window['go']['main']['App']['CheckFFmpeg']();
}

export function ConvertVideo(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ConvertVideo'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteTempFile(arg1) {
  return window['go']['main']['App']['DeleteTempFile'](arg1);
}

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function MergeVideoAudio(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['MergeVideoAudio'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SaveTempFile(arg1, arg2) {
  return window['go']['main']['App']['SaveTempFile'](arg1, arg2);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectFileWithFilter(arg1, arg2, arg3) {
  return window['go']['main']['App']['SelectFileWithFilter'](arg1, arg2, arg3);
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SelectOutputDir() {
  return window['go']['main']['App']['SelectOutputDir']();
}
