// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AdjustVolume(arg1:string,arg2:string,arg3:number,arg4:string):Promise<main.TaskResult>;

export function CheckFFmpeg():Promise<main.TaskResult>;

export function ConvertVideo(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.TaskResult>;

export function DeleteTempFile(arg1:string):Promise<void>;

export function GetFileInfo(arg1:string):Promise<main.TaskResult>;

export function MergeVideoAudio(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<main.TaskResult>;

export function SaveTempFile(arg1:string,arg2:Array<number>):Promise<main.FileInfo>;

export function SelectFile():Promise<main.FileInfo>;

export function SelectFileWithFilter(arg1:string,arg2:string,arg3:string):Promise<main.FileInfo>;

export function SelectFiles():Promise<main.MultipleFilesResult>;

export function SelectFolder():Promise<main.MultipleFilesResult>;

export function SelectOutputDir():Promise<main.DirResult>;
